
export const TEXTS_KEYS = {
  AUTH_INCORRECT_CREDENTIALS: "AUTH_INCORRECT_CREDENTIALS",

  EVENT_MISSING_ID_ON_NEWS: "EVENT_MISSING_ID_ON_NEWS",

  EP_INVALID_EVENT_ID: "EP_INVALID_EVENT_ID",
  EP_INVALID_CONFIRMATION_KEY: "EP_INVALID_CONFIRMATION_KEY",

  GALLERY_FILE_NOT_ALLOWED_TEMPLATE: "GALLERY_FILE_NOT_ALLOWED_TEMPLATE",

  HEALTH_CANT_QUERY_DB: "HEALTH_CANT_QUERY_DB",

  USER_USERNAME_TAKEN: "USER_USERNAME_TAKEN",
  USER_WRONG_CONFIRM_STR: "USER_WRONG_CONFIRM_STR",
  USER_NO_ACCOUNT: "USER_NO_ACCOUNT",

  CP_FILL_UP: "CP_FILL_UP",
  CP_EXISTING_CONTACT: "CP_EXISTING_CONTACT",

  MISSING_ADMIN_CREDENTIALS: "MISSING_ADMIN_CREDENTIALS",
  MISSING_ADMIN_OR_SUDO_CREDENTIALS: "MISSING_ADMIN_OR_SUDO_CREDENTIALS",
  MISSING_SUDO_CREDENTIALS: "MISSING_SUDO_CREDENTIALS,"
};
